// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: C3_Watch

#ifndef _C3_WATCH_UI_H
#define _C3_WATCH_UI_H

#define MAX_FACES 15
#define MAX_GAMES 5

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "osasys.h"
#include "ui_events.h"
extern lv_img_dsc_t ui_jpg_img_dsc;
extern lv_img_dsc_t ui_jpg_img_preview_dsc;
typedef struct {
    char*   system[4];
    char*   settings[8];
    char*   camera[4];
    char*   dialing[4];
    char*   ringing[4];
    char*   weather[2];
} ui_language_label_t;
extern ui_language_label_t watch_lable;

extern uint32_t lv_load_jpg(char *name,lv_img_dsc_t *img);
void pulseCall_Animation(lv_obj_t *TargetObject, int delay);
void analogSecond_Animation(lv_obj_t * TargetObject, int delay);

extern lv_anim_t secondsAnimation_0;
void ui_event_clockScreen(lv_event_t *e);
extern lv_obj_t *ui_clockScreen;
extern lv_obj_t *ui_hourLabel;
extern lv_obj_t *ui_minuteLabel;
extern lv_obj_t *ui_dateLabel;
extern lv_obj_t *ui_weatherIcon;
extern lv_obj_t *ui_weatherTemp;
extern lv_obj_t *ui_dayLabel;
extern lv_obj_t *ui_amPmLabel;
void ui_event_alertPanel(lv_event_t *e);
extern lv_obj_t *ui_alertPanel;
extern lv_obj_t *ui_alertIcon;
extern lv_obj_t *ui_alertText;
void ui_event_weatherScreen(lv_event_t *e);
extern lv_obj_t *ui_weatherScreen;
extern lv_obj_t *ui_weatherPanel;
extern lv_obj_t *ui_weatherCity;
extern lv_obj_t *ui_weatherCurrentIcon;
extern lv_obj_t *ui_weatherCurrentTemp;
extern lv_obj_t *ui_weatherUpdateTime;
extern lv_obj_t *ui_forecastPanel;
extern lv_obj_t *ui_forecastTitle;
extern lv_obj_t *ui_forecastList;

extern lv_obj_t *ui_alipayScreen;
extern lv_obj_t *ui_bindCodeScreen;

void ui_event_notificationScreen(lv_event_t *e);
extern lv_obj_t *ui_notificationScreen;
extern lv_obj_t *ui_messagePanel;
extern lv_obj_t *ui_messageIcon;
extern lv_obj_t *ui_messageTime;
extern lv_obj_t *ui_messageContent;
extern lv_obj_t *ui_messageList;
void ui_event_appListScreen(lv_event_t *e);
extern lv_obj_t *ui_appListScreen;
extern lv_obj_t *ui_appList;

void ui_event_gameListScreen(lv_event_t *e);
extern lv_obj_t *ui_gameListScreen;
extern lv_obj_t *ui_gameList;

void ui_event_alertStateSwitch(lv_event_t *e);
extern lv_obj_t *ui_alertStateLabel;
extern lv_obj_t *ui_alertStateSwitch;
extern lv_obj_t *ui_alertStateIcon;
extern lv_obj_t *ui_alertStatePanel;
void ui_event_settingsScreen(lv_event_t *e);
extern lv_obj_t *ui_settingsScreen;
extern lv_obj_t *ui_settingsList;
extern lv_obj_t *ui_settingsTitle;
extern lv_obj_t *ui_brightnessPanel;
void ui_event_brightnessSlider(lv_event_t *e);
extern lv_obj_t *ui_brightnessSlider;
extern lv_obj_t *ui_brightnessIcon;
extern lv_obj_t *ui_brightnessLabel;
extern lv_obj_t *ui_scrollingPanel;
extern lv_obj_t *ui_icon_scrolling;
void ui_event_scrollMode(lv_event_t *e);
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_scrollLabel;
extern lv_obj_t *ui_timeoutPanel;
void ui_event_timeoutSelect(lv_event_t *e);
extern lv_obj_t *ui_timeoutSelect;
extern lv_obj_t *ui_timeoutIcon;
extern lv_obj_t *ui_timeoutLabel;
extern lv_obj_t *ui_languagePanel;
void ui_event_languageSelect(lv_event_t *e);
extern lv_obj_t *ui_languageSelect;
extern lv_obj_t *ui_languageIcon;
extern lv_obj_t *ui_languageLabel;
extern lv_obj_t *ui_batteryPanel;
void ui_event_batterySlider(lv_event_t *e);
extern lv_obj_t *ui_batterySlider;
extern lv_obj_t *ui_batteryIcon;
extern lv_obj_t *ui_batteryLabel;
extern lv_obj_t *ui_aboutPanel;
extern lv_obj_t *ui_aboutIcon;
extern lv_obj_t *ui_aboutText;
void ui_event_kenyaPanel(lv_event_t *e);
extern lv_obj_t *ui_kenyaPanel;
extern lv_obj_t *ui_kenyaIcon;
extern lv_obj_t *ui_kenyaText;
void ui_event_screen_control(lv_event_t *e);
extern lv_obj_t *ui_controlScreen;
void ui_event_musicPlayButton(lv_event_t *e);
extern lv_obj_t *ui_musicPlayButton;
void ui_event_musicPrevButton(lv_event_t *e);
extern lv_obj_t *ui_musicPrevButton;
void ui_event_musicNextButton(lv_event_t *e);
extern lv_obj_t *ui_musicNextButton;
extern lv_obj_t *ui_btStateButton;
extern lv_obj_t *ui_searchPanel;
void ui_event_button_reserve(lv_event_t *e);
extern lv_obj_t *ui_reserveButton;
void ui_event_button_volumeUp(lv_event_t *e);
extern lv_obj_t *ui_volumeUpButton;
void ui_event_button_volumeDown(lv_event_t *e);
extern lv_obj_t *ui_volumeDownButton;
void ui_event_button_dial(lv_event_t *e);
extern lv_obj_t *ui_icon_btn_dial;

void ui_event_appInfoScreen(lv_event_t *e);
extern lv_obj_t *ui_appInfoScreen;
extern lv_obj_t *ui_appInfoPanel;
extern lv_obj_t *ui_appInfoTitle;
extern lv_obj_t *ui_appDetailsPanel;
extern lv_obj_t *ui_appDetailsIcon;
extern lv_obj_t *ui_appDetailsText;
extern lv_obj_t *ui_appConnectionPanel;
extern lv_obj_t *ui_appConnectionIcon;
extern lv_obj_t *ui_appConnectionText;
extern lv_obj_t *ui_appBatteryPanel;
extern lv_obj_t *ui_appBatteryIcon;
extern lv_obj_t *ui_appBatteryText;
extern lv_obj_t *ui_appBatteryLevel;

extern void ui_event_screen_dialpad(lv_event_t *e);
extern lv_obj_t *ui_dialpadScreen;
extern lv_obj_t *ui_dialpadLabel;
extern lv_obj_t *ui_dialMatrix;
extern const char *btn_dial_list[20];
void ui_event_screen_call(lv_event_t *e);
void ui_event_button_call(lv_event_t *e);
extern uint8_t phone_text_index;
extern lv_obj_t *ui_callScreen;
extern lv_obj_t *ui_callNumber;
extern lv_obj_t *ui_callLabel;
extern lv_obj_t *ui_callButton;
extern lv_obj_t *ui_callButtonText;
extern lv_obj_t *ui_callIcon;
extern lv_obj_t *ui_callPanel;

void ui_event_screen_ringing(lv_event_t *e);
void ui_event_button_ringing(lv_event_t *e);
extern lv_obj_t *ui_ringScreen;
extern lv_obj_t *ui_ringIcon;
extern lv_obj_t *ui_ringButton;
extern lv_obj_t *ui_ringButtonText;
extern lv_obj_t *ui_ringNumber;
extern lv_obj_t *ui_ringName;

void ui_filesScreen_screen_init(void);
extern lv_obj_t *ui_filesScreen;
extern lv_obj_t *ui_fileManagerPanel;
extern lv_obj_t *ui_driveInfoPanel;
extern lv_obj_t *ui_driveInfoIcon;
extern lv_obj_t *ui_driveInfoLabel;
extern lv_obj_t *ui_driveInfoBar;
extern lv_obj_t *ui_fileInfoPanel;
extern lv_obj_t *ui_fileInfoIcon;
extern lv_obj_t *ui_fileInfoName;
extern lv_obj_t *ui_fileInfoSize;
extern lv_obj_t *ui_folderInfoPanel;
extern lv_obj_t *ui_folderInfoIcon;
extern lv_obj_t *ui_folderInfoName;
extern lv_obj_t *ui_driveBackPanel;
extern lv_obj_t *ui_driveBackIcon;
extern lv_obj_t *ui_driveBackLabel;

extern lv_obj_t *ui_errorWindow;
extern lv_obj_t *ui_errorPanel;
extern lv_obj_t *ui_errorTitle;
extern lv_obj_t *ui_errorMessage;
void ui_event_errorClose(lv_event_t *e);
extern lv_obj_t *ui_errorClose;
extern lv_obj_t *ui_errorCloseText;

extern lv_obj_t *ui_home;
extern lv_obj_t *ui_faceSelect;

extern lv_obj_t *face_custom_root;

extern bool toAppList;
extern bool circular;
extern int numFaces;
extern int numGames;
extern int currentIndex;


#define CAPTURE_PREVIEW_IMG_WIDTH (64)
#define CAPTURE_PREVIEW_IMG_HEIGHT (64)
#define CAMERA_IMG_WIDTH (240)
#define CAMERA_IMG_HEIGHT (240)

void ui_event____initial_actions0(lv_event_t *e);
extern lv_obj_t *ui____initial_actions0;

typedef struct WatchFace
{
    const char *name;
    const lv_img_dsc_t *preview;
    lv_obj_t **watchface;
    bool custom;
    int customIndex;
} Face;

typedef struct DragEvent
{
    bool dragging;
    bool active;
    int x;
    int y;
} Drag;

extern Face faces[MAX_FACES];
extern Face games[MAX_GAMES];

void registerWatchface_cb(const char *name, const lv_img_dsc_t *preview, lv_obj_t **watchface);
void ui_update_watchfaces(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday,
                            int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);

void addNotificationList(int appId, const char *message, int index);
void addForecast(int day, int temp, int icon);
void addQrList(uint8_t id, const char *link);
void setWeatherIcon(lv_obj_t *obj, int id, bool day);
void setNotificationIcon(lv_obj_t *obj, int appId);
// void ui_games_update(void);
void showError(const char *title, const char *message);
void addWatchface(const char *name, const lv_img_dsc_t *src, int index);

void addListDrive(const char* name, int total, int used, lv_event_cb_t event_cb);
void addListDir(const char* name);
void addListFile(const char* name, int size);
void addListBack(lv_event_cb_t event_cb);

void addFaceList(lv_obj_t *parent, Face face);

void ui_init(void);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
