[config]
agbaud=3000000
dlbaud=115200

[control]
detect = 0
atreset = at+ecrst=delay,1000
atbaud = 115200
uart_timeout = 100
pullup_qspi = 1
debug = 0
dribble_dld_en = 1
usb_enable =  0
skip_addr_align = 0

[storage_cfg]
format_path = ./L511G_Y7PM_download/format_ec718pm.json.bin

[package_info]
pkgpath = ./L511G_Y7PM_download/L511G_Y7PM.binpkg

[agentboot]
agpath = ./image_ec718pm/agentboot_uart/agentboot.bin
ctrl = 6
; unit: MB
ap_size = 2
; unit: MB, 15 means none
cp_size = 15

[bootloader]
blpath = ./L511G_Y7PM_download/ap_bootloader.bin
burnaddr = 0x3000

[system]
syspath = ./L511G_Y7PM_download/ap_app_demo.bin
burnaddr = 0xbc000

[cp_system]
cp_syspath = ./L511G_Y7PM_download/cp-demo-flash.bin
burnaddr = 0x23000
storage_type=ap_flash

[flexfile0]
filepath = ./L511G_Y7PM_download/L511G-Y7_V1_EC718_RfCaliTable_v6.0_XP5733-41F_20260603.bin
burnaddr = 0x3e5000
storage_type=ap_flash


[otherfile1]
filepath = fs.fs
burnaddr = 0xb7c000
;ap_flash起始地址为0x800000，cp_flash起始地址为0x8800000
storage_type=ap_flash
		
[otherfile2]
filepath = ./L511G_Y7PM_download/L511G-Y7_V1_EC718_RfCaliTable_v6.0_XP5733-41F_20260603.bin
burnaddr = 0xe7000
storage_type=cp_flash

[otherfile3]

[otherfile4]

[otherfile5]
