{20, "callListDb", callList_init,               callList_proc},
{21, "callListDb", callListDialled_init,        callListDialled_proc},
{22, "callListDb", callListNewSms_init,         callListNewSm_proc},
{23, "callListDb", callListDetail_init,         callListDetail_proc},
{24, "callListDb", callListAddToContact_init,   callListAddToContact_proc},
{25, "callListDb", callListAddToBlockList_init, callListAddToBlockList_proc},
{26, "callListDb", callListDelete_init,         callListDelete_proc},
{27, "callListDb", callListDeleteAll_init,      callListDeleteAll_proc},