{10, "contactDb", contact_init,               contact_proc},
{11, "contactDb", add_contact_init,           add_contact_proc},
{12, "contactDb", del_contact_init,           del_contact_proc},
{13, "contactDb", copy_contact_init,          copy_contact_proc},
{14, "contactDb", move_contact_init,          move_contact_proc},
{15, "contactDb", set_contact_init,           set_contact_proc},
{16, "contactDb", import_export_contact_init, import_export_contact_proc},
{17, "contactDb", other_contact_init,         other_contact_proc},
