##########################################################################
#Mobiletek Software Version Information
##########################################################################
#sw version
CFLAGS += -DMBTK_PLAT_SW_VERSION=\"LYNQ_SDK_L511C_Y6E_V01.03.02_TY.08\"

#internal sw version
CFLAGS += -DMBTK_INTERNAL_SW_VERSION=\"LYNQ_SDK_L511C_Y6E_V01.03.02_TY.08\"

#Manufacturer
CFLAGS += -DMBTK_MANUFACTURER_ID=\"LYNQ\"

