##########################################################################
#Mobiletek Software Version Information
##########################################################################
#sw version
CFLAGS += -DMBTK_PLAT_SW_VERSION=\"LYNQ_SDK_L511C_Y7PM_V02.01b01_TY.07_demo20260803\"

#internal sw version
CFLAGS += -DMBTK_INTERNAL_SW_VERSION=\"LYNQ_SDK_L511C_Y7PM_V02.01b01_TY.07_demo20260803\"

#Manufacturer
CFLAGS += -DMBTK_MANUFACTURER_ID=\"LYNQ\"

