/**
 * @file tkl_pwm.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_pwm.h"
#include "tuya_error_code.h"
#include "vlog.h"

#include "ol_pwm_api.h"
#include "ol_gpio_api.h"

#define PWM_NUM 5

typedef struct{
    int mbtk_pin;
    ol_pwm_num chId;
    ol_gpio_func_enum func;
    ol_gpio_func_enum orgFunc;
    bool startflag;
}pwm_map_t;

static pwm_map_t pwm_map[PWM_NUM] = {
    { mbtk_pin_28, OL_PWM_NUM_0, OL_GPIO_FUNC3, OL_GPIO_FUNC2 },          
    { mbtk_pin_29, OL_PWM_NUM_1, OL_GPIO_FUNC3, OL_GPIO_FUNC2 },            
    { mbtk_pin_25, OL_PWM_NUM_2, OL_GPIO_FUNC3, OL_GPIO_FUNC0 },            
    { mbtk_pin_20, OL_PWM_NUM_3, OL_GPIO_FUNC3, OL_GPIO_FUNC0 },         
    { mbtk_pin_16, OL_PWM_NUM_4, OL_GPIO_FUNC3, OL_GPIO_FUNC0 },            
};

static TUYA_PWM_BASE_CFG_T pwm_cfg[PWM_NUM] = {0};
// --- END: user defines and implements ---

/**
 * @brief pwm init
 *
 * @param[in] ch_id: pwm channal id, id index starts at 0
 * @param[in] cfg: pwm config
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_init(TUYA_PWM_NUM_E ch_id, const TUYA_PWM_BASE_CFG_T *cfg)
{
    // --- BEGIN: user implements ---
    if (ch_id >= PWM_NUM) {
        LOGE("tkl_pwm_init failed, invalid ch_id(%d)", ch_id);
        return OPRT_INVALID_PARM;
    }

    if (NULL == cfg) {
        LOGE("tkl_pwm_init failed, cfg null");
        return OPRT_INVALID_PARM;
    }

    ol_gpio_config_struct gpio_cfg;
    memset(&gpio_cfg, 0, sizeof(gpio_cfg));
    gpio_cfg.gpio_func = pwm_map[ch_id].func;
    int ret = ol_pin_config(pwm_map[ch_id].mbtk_pin, &gpio_cfg);
    if (0 != ret) {
        LOGE("init pwm %d failed, set pin mux failed, ret/%d", ch_id, ret);
        return OPRT_COM_ERROR;
    }
    memcpy(&pwm_cfg[ch_id], cfg, sizeof(*cfg));
    pwm_map[ch_id].startflag = false;
    LOGD("init pwm %d success, duty/%u, freq/%u", ch_id, cfg->duty, cfg->frequency);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief pwm deinit
 *
 * @param[in] ch_id: pwm channal id, id index starts at 0
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_deinit(TUYA_PWM_NUM_E ch_id)
{
    // --- BEGIN: user implements ---
    if (ch_id >= PWM_NUM) {
        LOGE("tkl_pwm_deinit failed, invalid ch_id(%d)", ch_id);
        return OPRT_INVALID_PARM;
    }

    ol_gpio_config_struct cfg;
    memset(&cfg, 0, sizeof(cfg));
    cfg.gpio_func = pwm_map[ch_id].orgFunc;
    int ret = ol_pin_config(pwm_map[ch_id].mbtk_pin, &cfg);
    if (0 != ret) {
        LOGE("pwm %d deinit failed, restore mux pin failed, ret/%d", ch_id, ret);
        return OPRT_COM_ERROR;
    }

    memset(&pwm_cfg[ch_id], 0, sizeof(TUYA_PWM_BASE_CFG_T));
    LOGD("pwm %d deinit success", ch_id);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief pwm start
 *
 * @param[in] ch_id: pwm channal id, id index starts at 0
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_start(TUYA_PWM_NUM_E ch_id)
{
    // --- BEGIN: user implements ---
    if (ch_id >= PWM_NUM) {
        LOGE("tkl_pwm_start failed, invalid ch_id(%d)", ch_id);
        return OPRT_INVALID_PARM;
    }

    if(pwm_map[ch_id].startflag) {
        return OPRT_OK;
    }

    unsigned long duty_cycle = pwm_cfg[ch_id].duty * 100 / (1e6 / pwm_cfg[ch_id].frequency);
    duty_cycle = duty_cycle > 100 ? 100 : duty_cycle;
    int ret = ol_pwm_enable(pwm_map[ch_id].chId, pwm_cfg[ch_id].frequency, duty_cycle);
    if (0 != ret) {
        LOGE("start pwm %d failed, enable pwm failed, ret/%d", ch_id, ret);
        return OPRT_COM_ERROR;
    }
    pwm_map[ch_id].startflag = true;
    LOGD("start pwm %d %d success", ch_id, duty_cycle);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief pwm stop
 *
 * @param[in] ch_id: pwm channal id, id index starts at 0
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_stop(TUYA_PWM_NUM_E ch_id)
{
    // --- BEGIN: user implements ---
    if (ch_id >= PWM_NUM) {
        LOGE("tkl_pwm_stop failed, invalid ch_id(%d)", ch_id);
        return OPRT_INVALID_PARM;
    }

    if(!pwm_map[ch_id].startflag) {
        return OPRT_OK;
    }

    int ret = ol_pwm_disable(pwm_map[ch_id].chId);
    if (0 != ret) {
        LOGE("stop pwm %d failed, ret/%d", ch_id, ret);
        return OPRT_COM_ERROR;
    }
    pwm_map[ch_id].startflag = false;
    LOGD("stop pwm %d success", ch_id);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief multiple pwm channel start
 *
 * @param[in] ch_id: pwm channal id list
 * @param[in] num  : num of pwm channal to start
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_multichannel_start(TUYA_PWM_NUM_E *ch_id, uint8_t num)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief multiple pwm channel stop
 *
 * @param[in] ch_id: pwm channal id list
 * @param[in] num  : num of pwm channal to stop
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_multichannel_stop(TUYA_PWM_NUM_E *ch_id, uint8_t num)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief pwm duty set
 *
 * @param[in] ch_id: pwm channal id, id index starts at 0
 * @param[in] duty:  pwm duty cycle
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_duty_set(TUYA_PWM_NUM_E ch_id, uint32_t duty)
{
    // --- BEGIN: user implements ---
    if (ch_id >= PWM_NUM) {
        LOGE("tkl_pwm_duty_set failed, invalid ch_id(%d)", ch_id);
        return OPRT_INVALID_PARM;
    }

    if(!pwm_map[ch_id].startflag) {
        return OPRT_COM_ERROR;
    }

    unsigned long duty_cycle = duty * 100 / (1e6 / pwm_cfg[ch_id].frequency);
    duty_cycle = duty_cycle > 100 ? 100 : duty_cycle;
    int ret = ol_pwm_updatedutycycle(pwm_map[ch_id].chId, duty_cycle);
    if (0 != ret) {
        LOGE("set pwm %d duty(%d) failed, ret/%d", ch_id, duty, ret);
        return OPRT_COM_ERROR;
    }

    pwm_cfg[ch_id].duty = duty;
    LOGD("set pwm %d duty(%d) success", ch_id, duty);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief pwm frequency set
 *
 * @param[in] ch_id: pwm channal id, id index starts at 0
 * @param[in] frequency: pwm frequency
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_frequency_set(TUYA_PWM_NUM_E ch_id, uint32_t frequency)
{
    // --- BEGIN: user implements ---
    if (ch_id >= PWM_NUM) {
        LOGE("tkl_pwm_frequency_set failed, invalid ch_id(%d)", ch_id);
        return OPRT_INVALID_PARM;
    }

    tkl_pwm_stop(ch_id);
    unsigned long duty_cycle = pwm_cfg[ch_id].duty * 100 / (1e6 / pwm_cfg[ch_id].frequency);
    pwm_cfg[ch_id].frequency = frequency;    
    pwm_cfg[ch_id].duty = (1e6 / pwm_cfg[ch_id].frequency) * duty_cycle / 100;
    LOGD("set pwm %d frequency(%d) success, duty:%d", ch_id, frequency, pwm_cfg[ch_id].duty);
    return tkl_pwm_start(ch_id);
    // --- END: user implements ---
}

/**
 * @brief pwm polarity set
 *
 * @param[in] ch_id: pwm channal id, id index starts at 0
 * @param[in] polarity: pwm polarity
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_polarity_set(TUYA_PWM_NUM_E ch_id, TUYA_PWM_POLARITY_E polarity)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief set pwm info
 *
 * @param[in] ch_id: pwm channal id, id index starts at 0
 * @param[in] info: pwm info
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_info_set(TUYA_PWM_NUM_E ch_id, const TUYA_PWM_BASE_CFG_T *info)
{
    // --- BEGIN: user implements ---
    if (ch_id >= PWM_NUM) {
        LOGE("tkl_pwm_info_set failed, invalid ch_id(%d)", ch_id);
        return OPRT_INVALID_PARM;
    }

    if (NULL == info) {
        LOGE("tkl_pwm_info_set failed, info null");
        return OPRT_INVALID_PARM;
    }

    tkl_pwm_stop(ch_id);
    memcpy(&pwm_cfg[ch_id], info, sizeof(TUYA_PWM_BASE_CFG_T));
    return tkl_pwm_start(ch_id);
    // --- END: user implements ---
}

/**
 * @brief get pwm info
 *
 * @param[in] ch_id: pwm channal id, id index starts at 0
 * @param[out] info: pwm info
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_info_get(TUYA_PWM_NUM_E ch_id, TUYA_PWM_BASE_CFG_T *info)
{
    // --- BEGIN: user implements ---
    if (ch_id >= PWM_NUM) {
        LOGE("tkl_pwm_info_get failed, invalid ch_id(%d)", ch_id);
        return OPRT_INVALID_PARM;
    }

    if (NULL == info) {
        LOGE("tkl_pwm_info_get failed, info null");
        return OPRT_INVALID_PARM;
    }

    memcpy(info, &pwm_cfg[ch_id], sizeof(TUYA_PWM_BASE_CFG_T));
    LOGD("get pwm %d info success", ch_id);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief pwm capture mode start
 *
 * @param[in] ch_id: pwm channal id, id index starts at 0
 * @param[in] cfg: pwm capture irq config
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_cap_start(TUYA_PWM_NUM_E ch_id, const TUYA_PWM_CAP_IRQ_T *cfg)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief pwm capture mode stop
 *
 * @param[in] ch_id: pwm channal id, id index starts at 0
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_pwm_cap_stop(TUYA_PWM_NUM_E ch_id)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

