/**
 * @file tkl_cellular_player.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */
#include "tkl_cellular_player.h"
#include "vlog.h"

/**
 * @brief 播放一个音频文件
 * @param type  audio 播放类型
 * 注意：当类型为TKL_AUDEV_PLAY_TYPE_VOICE时候，音频源只支持8K采样率，8bit/16bit/32bit,
 * 单声道。否则播放的声音异常
 * @param format    音频文件格式
 * @param file_path 音频文件（需要包含完整的路径）
 * @param cb        播放的事件回调函数
 * @param cb_ctx    回调函数的参数
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_start(TKL_AUDIO_PLAYER_TYPE_E type,
                                      TKL_AUDIO_STREAM_FORMAT_E format,
                                      PCHAR_T file_path,
                                      TKL_AUDIO_PLAYER_CB cb, PVOID_T cb_ctx)
{
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 暂停正在播放的音频
 * @param 无
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_pause(VOID)
{
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 恢复暂停的的音频
 * @param 无
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_resume(VOID)
{
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 停止正在播放的的音频
 * @param 无
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_stop(VOID)
{
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 设置音频播放的音量
 * @param vol （0~100）
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_set_vol(INT_T vol)
{
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 获取音频播放的音量
 * @param vol （0~100）
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_get_vol(PINT_T vol)
{
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 设置音频输出设备的是否静音。这个属性不会被保存到flash中。
 * 每次重启后，都会变成非静音
 * @param mute : TRUE 静音
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_set_mute(BOOL_T mute)
{
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 获取音频输出设备的是否静音。
 * @param mute : TRUE 静音
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_get_mute(PBOOL_T mute)
{
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 播放一个音频内存
 * @param type  audio 播放类型.
 * 注意：当类型为TKL_AUDEV_PLAY_TYPE_VOICE时候，音频源只支持8K采样率，8bit/16bit/32bit,
 * 单声道。否则播放的声音异常
 * @param format    音频文件格式
 * @param buff 音频内存数据指针
 * @param size 音频数据大小
 * @param cb        播放的事件回调函数
 * @param cb_ctx    回调函数的参数
 * @return 0 成功，其他失败
 */

OPERATE_RET tkl_cellular_player_mem_start(TKL_AUDIO_PLAYER_TYPE_E type,
                                          TKL_AUDIO_STREAM_FORMAT_E format,
                                          PBYTE_T buff, UINT_T size,
                                          TKL_AUDIO_PLAYER_CB cb, PVOID_T cb_ctx)
{
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 设置音频输出设备
 * @param channle TKL_AUDEV_OUTPUT_TYPE
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_set_audio_output(TKL_AUDEV_OUTPUT_TYPE chan)
{
    LOGE("tkl_cellular_player_set_audio_output not support");
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 获取音频输出设备
 * @param channle TKL_AUDEV_OUTPUT_TYPE
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_get_audio_output(TKL_AUDEV_OUTPUT_TYPE* chan)
{
    LOGE("tkl_cellular_player_get_audio_output not support");
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 设置音频输入设备
 * @param channle TKL_AUDEV_INPUT_TYPE
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_set_audio_input(TKL_AUDEV_INPUT_TYPE chan)
{
    LOGE("tkl_cellular_player_set_audio_input not support");
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 获取音频输入设备
 * @param channle TKL_AUDEV_INPUT_TYPE
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_get_audio_input(TKL_AUDEV_INPUT_TYPE* chan)
{
    LOGE("tkl_cellular_player_get_audio_input not support");
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 获取音频当前的播放状态
 * @param status TKL_AUDIO_PLAYER_STATUS_E
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_get_status(TKL_AUDIO_PLAYER_STATUS_E* status)
{
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 播放流媒体音频
 * @param type TKL_AUDIO_PLAYER_TYPE_E
 * 注意：当类型为TKL_AUDEV_PLAY_TYPE_VOICE时候，音频源只支持8K采样率，16bit,
 * 单声道。否则播放的声音异常
 * @param playOps 参考 \p TKL_AUDIO_PLAY_OPS_T
 * @param playCtx playOps回调函数的输入参数
 * @param frame 音频帧，只有流信息会被使用到。具体参考 \p TKL_AUDIO_PLAYER_TYPE_E
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_start_stream(TKL_AUDIO_PLAYER_TYPE_E type,
        CONST TKL_AUDIO_PLAY_OPS_T* playOps,
        PVOID_T playCtx,
        CONST TKL_AUDIO_FRAME_T* frame)
{
    LOGE("tkl_cellular_player_start_stream not support!");
    return OPRT_NOT_SUPPORTED;
}

/**
 * @brief 停止流媒体播放
 *
 * @return 0 成功，其他失败
 */
OPERATE_RET tkl_cellular_player_stop_stream(VOID)
{
    LOGE("tkl_cellular_player_stop_stream not support!");
    return OPRT_NOT_SUPPORTED;
}
