/**
 * @file tkl_semaphore.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_semaphore.h"
#include "tuya_error_code.h"

#include "cmsis_os2.h"
#include "vlog.h"
// --- END: user defines and implements ---

/**
 * @brief Create semaphore
 *
 * @param[out] handle: semaphore handle
 * @param[in] sem_cnt: semaphore init count
 * @param[in] sem_max: semaphore max count
 *
 * @note This API is used for creating semaphore.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_semaphore_create_init(TKL_SEM_HANDLE *handle, uint32_t sem_cnt, uint32_t sem_max)
{
    // --- BEGIN: user implements ---
	if (!handle) {
		LOGE("create semaphore failed, handle null");
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}
	
	if (sem_cnt > sem_max) {
		LOGE("create semaphore failed, invalid semCnt(%u:%u)", sem_cnt, sem_max);
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}
	
	osSemaphoreId_t id = osSemaphoreNew(sem_max, sem_cnt, NULL);
	if (NULL == id) {
		LOGE("create semaphore failed");
		return OPRT_COM_ERROR;
	}

	*handle = id;
	return OPRT_OK;
	// --- END: user implements ---
}

/**
 * @brief Wait semaphore
 *
 * @param[in] handle: semaphore handle
 * @param[in] timeout: wait timeout, bet: ms. SEM_WAIT_FOREVER means wait until get semaphore
 *
 * @note This API is used for waiting semaphore.
 *
 * @return OPRT_OK on success.OPRT_OS_ADAPTER_SEM_WAIT_TIMEOUT means timeout. Others on error, please refer to
 * tuya_error_code.h
 */
OPERATE_RET tkl_semaphore_wait(const TKL_SEM_HANDLE handle, uint32_t timeout)
{
    // --- BEGIN: user implements ---
	if (!handle) {
		LOGE("semaphore wait failed, invalid handle");
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}
	
	osStatus_t status = osSemaphoreAcquire(handle, timeout);
	if (osErrorResource == status || osErrorParameter == status) {
		// LOGE("semaphore wait failed, status: %d", status);
		return OPRT_OS_ADAPTER_INVALID_PARM;
	} else if (osErrorTimeout == status) {
		return OPRT_OS_ADAPTER_SEM_WAIT_FAILED;
	}

	return OPRT_OK;
	// --- END: user implements ---
}

/**
 * @brief Post semaphore
 *
 * @param[in] handle: semaphore handle
 *
 * @note This API is used for posting semaphore.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_semaphore_post(const TKL_SEM_HANDLE handle)
{
    // --- BEGIN: user implements ---
	if (!handle) {
		LOGE("semaphore post failed, invalid handle");
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}

	osStatus_t status = osSemaphoreRelease(handle);
	return (osOK == status) ? OPRT_OK : OPRT_COM_ERROR;
	// --- END: user implements ---
}

/**
 * @brief Release semaphore
 *
 * @param[in] handle: semaphore handle
 *
 * @note This API is used for releasing semaphore.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_semaphore_release(const TKL_SEM_HANDLE handle)
{
    // --- BEGIN: user implements ---
	if (!handle) {
		LOGE("semaphore release failed, invalid handle");
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}

	osStatus_t status = osSemaphoreDelete(handle);
	return (osOK == status) ? OPRT_OK : OPRT_COM_ERROR;
	// --- END: user implements ---
}

