/**
 * @file tkl_mutex.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_mutex.h"
#include "tuya_error_code.h"

#include "cmsis_os2.h"
#include "vlog.h"

#undef LOGD
#define LOGD(fmt, ...) 
// --- END: user defines and implements ---

/**
 * @brief Create mutex
 *
 * @param[out] pMutexHandle: mutex handle
 *
 * @note This API is used to create and init a recursive mutex.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_mutex_create_init(TKL_MUTEX_HANDLE *pMutexHandle)
{
    // --- BEGIN: user implements ---
	if (!pMutexHandle) {
		LOGE("create mutex failed, para is null");
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}

	osMutexAttr_t attr = {
		.name = NULL,
		.attr_bits = osMutexRecursive,
		.cb_mem = NULL,
		.cb_size = 0,
	};
	
	osMutexId_t id = osMutexNew(&attr);
	if (NULL == id) {
		LOGE("create mutex failed");
		return OPRT_COM_ERROR;
	}

	*pMutexHandle = id;
	LOGD("create mutex success");
	return OPRT_OK;
	// --- END: user implements ---
}

/**
 * @brief Lock mutex
 *
 * @param[in] mutexHandle: mutex handle
 *
 * @note This API is used to lock a recursive mutex.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_mutex_lock(const TKL_MUTEX_HANDLE mutexHandle)
{
    // --- BEGIN: user implements ---
	if (!mutexHandle) {
		LOGE("mutex lock failed, invalid param");
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}

	osStatus_t status = osMutexAcquire(mutexHandle, osWaitForever);
	if (osOK != status) {
		LOGE("mutex lock failed, status: %d", status);
		return OPRT_COM_ERROR;
	}

	return OPRT_OK;
	// --- END: user implements ---
}

/**
 * @brief Try Lock mutex
 *
 * @param[in] mutexHandle: mutex handle
 *
 * @note This API is used to try lock a recursive mutex.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_mutex_trylock(const TKL_MUTEX_HANDLE mutexHandle)
{
    // --- BEGIN: user implements ---
	if (!mutexHandle) {
		LOGE("mutex try lock failed, invalid param");
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}

	osStatus_t status = osMutexAcquire(mutexHandle, 0);
	if (osOK != status) {
		LOGE("mutex try lock failed");
		return OPRT_OS_ADAPTER_MUTEX_LOCK_FAILED;
	}

	return OPRT_OK;
	// --- END: user implements ---
}

/**
 * @brief Unlock mutex
 *
 * @param[in] mutexHandle: mutex handle
 *
 * @note This API is used to unlock a recursive mutex.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_mutex_unlock(const TKL_MUTEX_HANDLE mutexHandle)
{
    // --- BEGIN: user implements ---
	if (!mutexHandle) {
		LOGE("mutex unlock failed, invalid param");
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}
	
	osStatus_t status = osMutexRelease(mutexHandle);
	if (osOK != status) {
		LOGE("mutex unlock failed, status: %d", status);
		return OPRT_COM_ERROR;
	}
	
	LOGD("mutex unlock success");
	return OPRT_OK;
	// --- END: user implements ---
}

/**
 * @brief Release mutex
 *
 * @param[in] mutexHandle: mutex handle
 *
 * @note This API is used to release a recursive mutex.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_mutex_release(const TKL_MUTEX_HANDLE mutexHandle)
{
    // --- BEGIN: user implements ---
	if (!mutexHandle) {
		LOGE("mutex release failed, invalid param");
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}
	
	osStatus_t status = osMutexDelete(mutexHandle);
	if (osOK != status) {
		LOGE("mutex release failed, status: %d", status);
		return OPRT_COM_ERROR;
	}
	
	LOGD("mutex release success");
	return OPRT_OK;
	// --- END: user implements ---
}

