/**
 * @file tkl_system.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_system.h"
#include "tuya_error_code.h"

#include "cmsis_os2.h"
#include "reset.h"
#include "ol_open_api.h"
#include "vlog.h"


extern void ol_power_reset(void);

// --- END: user defines and implements ---

/**
 * @brief system reset
 *
 * @param none
 *
 * @return none
 */
void tkl_system_reset(void)
{
    // --- BEGIN: user implements ---
    ol_power_reset();
    // --- END: user implements ---
}

/**
 * @brief Get system tick count
 *
 * @param none
 *
 * @return system tick count
 */
SYS_TICK_T tkl_system_get_tick_count(void)
{
    // --- BEGIN: user implements ---
    return osKernelGetTickCount();
    // --- END: user implements ---
}

/**
 * @brief Get system millisecond
 *
 * @param none
 *
 * @return system millisecond
 */
SYS_TIME_T tkl_system_get_millisecond(void)
{
    // --- BEGIN: user implements ---
    return TICKS_TO_MILLISECONDS(osKernelGetTickCount());
    // --- END: user implements ---
}

/**
 * @brief Get system random data
 *
 * @param[in] range: random from 0  to range
 *
 * @return random value
 */
int tkl_system_get_random(uint32_t range)
{
    // --- BEGIN: user implements ---
	static bool seed_flag = false;
	if(seed_flag == false) {
		seed_flag = true;
		srand(osKernelGetTickCount());
	}
    
	int data = rand();
	return (int)((unsigned int)data % range);

	// --- END: user implements ---
}

/**
 * @brief Get system reset reason
 *
 * @param[in] describe: point to reset reason describe
 *
 * @return reset reason
 */
TUYA_RESET_REASON_E tkl_system_get_reset_reason(char **describe)
{
    // --- BEGIN: user implements ---
    LastResetState_e ap_state, cp_state;
	ResetStateGet(&ap_state, &cp_state);
	
	TUYA_RESET_REASON_E reason = TUYA_RESET_REASON_UNKNOWN;
	switch (ap_state) {
		case LAST_RESET_POR:
		case LAST_RESET_PAD:
			reason = TUYA_RESET_REASON_POWERON; break;
		case LAST_RESET_SWRESET:
			reason = TUYA_RESET_REASON_SOFTWARE; break;
		case LAST_RESET_HARDFAULT:
			reason = TUYA_RESET_REASON_FAULT; break;
		case LAST_RESET_ASSERT:
		case LAST_RESET_LOCKUP:
			reason = TUYA_RESET_REASON_CRASH; break;
		case LAST_RESET_WDTSW:
			reason = TUYA_RESET_REASON_SW_WDOG; break;
		case LAST_RESET_WDTHW:
		case LAST_RESET_AONWDT:
			reason = TUYA_RESET_REASON_HW_WDOG; break;
		case LAST_RESET_BATLOW:
		case LAST_RESET_TEMPHI:
			reason = TUYA_RESET_REASON_EXTERNAL; break;
		case LAST_RESET_FOTA:
			reason = TUYA_RESET_REASON_BOOTLOADER; break;
		case LAST_RESET_UNKNOWN:
			reason = TUYA_RESET_REASON_UNKNOWN; break;
		case LAST_RESET_MAXNUM:
		default:
			reason = TUYA_RESET_REASON_UNSUPPORT; break;
	}

	LOGD("tuya boot cause, ap/%d, cp/%d, ty_cause: %d", ap_state, cp_state, reason);
	return reason;
    // --- END: user implements ---
}

/**
 * @brief  system sleep
 *
 * @param[in] describe: num ms
 *
 * @return none
 */
void tkl_system_sleep(uint32_t num_ms)
{
    // --- BEGIN: user implements ---
    osDelay(num_ms);
    // --- END: user implements ---
}

/**
 * @brief system delay
 *
 * @param[in] msTime: time in MS
 *
 * @note This API is used for system sleep.
 *
 * @return void
 */
void tkl_system_delay(uint32_t num_ms)
{
    // --- BEGIN: user implements ---
    osDelay(num_ms);
    // --- END: user implements ---
}

/**
 * @brief get system cpu info
 *
 * @param[in] cpu_ary: info of cpus
 * @param[in] cpu_cnt: num of cpu
 * @note This API is used for system cpu info get.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */

OPERATE_RET tkl_system_get_cpu_info(TUYA_CPU_INFO_T **cpu_ary, int *cpu_cnt)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

