/**
 * @file tkl_memory.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_memory.h"
#include "tuya_error_code.h"

#include "cmsis_os2.h"
#include "vlog.h"
#include "os_common.h"

// --- END: user defines and implements ---

/**
 * @brief Alloc memory of system
 *
 * @param[in] size: memory size
 *
 * @note This API is used to alloc memory of system.
 *
 * @return the memory address malloced
 */
void *tkl_system_malloc(size_t size)
{
    // --- BEGIN: user implements ---
    void *ptr = malloc(size);
    if(ptr == NULL) {
        LOGE("malloc failed, size: %d", size);
    }
    return ptr;
    // --- END: user implements ---
}

/**
 * @brief Free memory of system
 *
 * @param[in] ptr: memory point
 *
 * @note This API is used to free memory of system.
 *
 * @return void
 */
void tkl_system_free(void *ptr)
{
    // --- BEGIN: user implements ---
    if (ptr) {
        free(ptr);
    }
    // --- END: user implements ---
}

/**
* @brief set memory
*
* @param[in] size: memory size
*
* @note This API is used to alloc memory of system.
*
* @return the memory address malloced
*/
void *tkl_system_memset(void* src, int ch, const size_t n)
{
    // --- BEGIN: user implements ---
    return memset(src, ch, n);
    // --- END: user implements ---
}

/**
* @brief Alloc memory of system
*
* @param[in] size: memory size
*
* @note This API is used to alloc memory of system.
*
* @return the memory address malloced
*/
void *tkl_system_memcpy(void* src, const void* dst, const size_t n)
{
    // --- BEGIN: user implements ---
	return memcpy(src, dst, n);
    // --- END: user implements ---
}

/**
 * @brief Allocate and clear the memory
 *
 * @param[in]       nitems      the numbers of memory block
 * @param[in]       size        the size of the memory block
 *
 * @return the memory address calloced
 */
void *tkl_system_calloc(size_t nitems, size_t size)
{
    // --- BEGIN: user implements ---
    return calloc(nitems, size);
    // --- END: user implements ---
}

/**
 * @brief Re-allocate the memory
 *
 * @param[in]       nitems      source memory address
 * @param[in]       size        the size after re-allocate
 *
 * @return void
 */
void *tkl_system_realloc(void *ptr, size_t size)
{
    // --- BEGIN: user implements ---
	return NULL;
    // --- END: user implements ---
}

/**
 * @brief Get system free heap size
 *
 * @param none
 *
 * @return heap size
 */
int tkl_system_get_free_heap_size(void)
{
    // --- BEGIN: user implements ---
    return (int)xPortGetFreeHeapSizeEc();
    // --- END: user implements ---
}

/**
 * @brief Compare two pieces of memory
 *
 * @param[in]       str1        memory 1
 * @param[in]       str2        memory 2
 * @param[in]       n           number of comparisons
 *
 * @return 0 means that the two pieces of memory are the same
 */
int tkl_system_memcmp(const void *str1, const void *str2, size_t n)
{
    // --- BEGIN: user implements ---
    return memcmp(str1, str2, n);
    // --- END: user implements ---
}

