/**
 * @file tkl_cellular_vbat.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_cellular_vbat.h"
#include "tuya_error_code.h"
#include "tkl_output.h"
#if !defined(ENABLE_CELLULAR_PLUGIN) || ENABLE_CELLULAR_PLUGIN == 0
#if defined(ENABLE_CELLULAR_VBAT) && ENABLE_CELLULAR_VBAT == 1

#include "ol_adc_api.h"
#define LOGE(fmt, ...)  tkl_log_output("[tkl_cell_vbat][ERR/%d]: " fmt "\r\n", __LINE__, ##__VA_ARGS__)
// --- END: user defines and implements ---

/**
 * @brief 获取电池剩余电量百分比
 *
 * @param rsoc 剩余电量百分比
 *
 * @return OPRT_OK 获取成功 其它 获取失败
 */
OPERATE_RET tkl_cellular_vbat_get_rsoc(uint8_t* rsoc)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 获取电池电压
 *
 * @param voltage 当前电池电压，单位mV
 *
 * @return OPRT_OK 获取成功 其它 获取失败
 */
OPERATE_RET tkl_cellular_vbat_get_voltage(uint32_t* voltage)
{
    
    int ret = ol_adc_get_vol(OL_ADC_VBAT) / 1000;
    if (ret < 0) {
        LOGE("vbat get voltage failed, ret: %d", ret);
        return OPRT_COM_ERROR;
    }

    *voltage = ret;
    return OPRT_OK;
}

/**
 * @brief 设置是否开启NTC检测电池温度
 *
 * @param enable NTC检测电池温度开/关
 *
 * @return OPRT_OK 设置成功 其它 设置失败
 */
OPERATE_RET tkl_cellular_vbat_ntc_enable(bool enable)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 设置恒流充电阶段，电池充电电流
 *
 * @param current 充电电流，单位毫安（mA)
 *
 * @return OPRT_OK 设置成功 其它 设置失败
 */
OPERATE_RET tkl_cellular_vbat_set_charge_current(uint32_t current)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 获取充电器状态
 *
 * @param 无
 *
 * @return 充电器状态，查看 @TKL_CELLULAR_VBAT_CHG_STATE_E定义
 */
TKL_CELLULAR_VBAT_CHG_STATE_E tkl_cellular_vbat_get_charger_state(void)
{
    // --- BEGIN: user implements ---
    return 0;
    // --- END: user implements ---
}

/**
 * @brief 注册电池及充电器消息回调处理函数
 *
 * @param callback 回调函数
 *
 * @return 0 注册成功 其它 注册失败
 */
OPERATE_RET tkl_cellular_vbat_cb_register(TKL_CELLULAR_VBAT_CHARGE_CB callback)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief 是否开启电池低电压关机功能
 *
 * @param enable TRUE 开启，FLASE关闭
 *
 * @return OPRT_OK 设置成功 其它 设置失败
 */
OPERATE_RET tkl_cellular_vbat_low_volt_poweroff_enable(bool enable)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

// --- BEGIN: user defines and implements ---
#endif
#endif
// --- END: user defines and implements ---
