/**
 * @file tkl_queue.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_queue.h"
#include "tuya_error_code.h"

#include "cmsis_os2.h"
#include "vlog.h"

// --- END: user defines and implements ---

/**
 * @brief Create message queue
 *
 * @param[in] msgsize message size
 * @param[in] msgcount message number
 * @param[out] queue the queue handle created
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_queue_create_init(TKL_QUEUE_HANDLE *queue, int msgsize, int msgcount)
{
    // --- BEGIN: user implements ---
	if (!queue) {
		LOGE("create queue failed, queue is null");
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}
	
	if (0 >= msgsize || 0 >= msgcount) {
		LOGE("invalid msgsize or msgcount, msgsize: %d, msgcount: %d", msgsize, msgcount);
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}
	
	osMessageQueueId_t id = osMessageQueueNew((uint32_t)msgcount, (uint32_t)msgsize, NULL);
	if (NULL == id) {
		LOGE("create queue failed");
		return OPRT_OS_ADAPTER_QUEUE_CREAT_FAILED;
	}
	
	*queue = id;
	return OPRT_OK;
	// --- END: user implements ---
}

/**
 * @brief post a message to the message queue
 *
 * @param[in] queue the handle of the queue
 * @param[in] data the data of the message
 * @param[in] timeout timeout time
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_queue_post(const TKL_QUEUE_HANDLE queue, void *data, uint32_t timeout)
{
    // --- BEGIN: user implements ---
	if (!queue || !data) {
		LOGE("queue post failed, invalid param, queue: %p, msg: %p", queue, data);
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}
	
	osStatus_t status = osMessageQueuePut(queue, data, 0, timeout);
	return (osOK == status) ? OPRT_OK : OPRT_OS_ADAPTER_QUEUE_SEND_FAIL;
	// --- END: user implements ---
}

/**
 * @brief fetch message from the message queue
 *
 * @param[in] queue the message queue handle
 * @param[inout] msg the message fetch form the message queue
 * @param[in] timeout timeout time
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_queue_fetch(const TKL_QUEUE_HANDLE queue, void *msg, uint32_t timeout)
{
    // --- BEGIN: user implements ---
	if (!queue || !msg) {
		LOGE("queue fetch failed, invalid param, queue: %p, msg: %p", queue, msg);
		return OPRT_OS_ADAPTER_INVALID_PARM;
	}

	osStatus_t status = osMessageQueueGet(queue, msg, NULL, timeout);
	return (osOK == status) ? OPRT_OK : OPRT_OS_ADAPTER_QUEUE_RECV_FAIL;
	// --- END: user implements ---
}

/**
 * @brief free the message queue
 *
 * @param[in] queue the message queue handle
 *
 * @return void
 */
void tkl_queue_free(const TKL_QUEUE_HANDLE queue)
{
    // --- BEGIN: user implements ---
	if (!queue) {
		LOGE("queue free failed, invalid param");
		return;
	}
	
	osStatus_t status = osMessageQueueDelete(queue);
	if (osOK != status) {
		LOGE("queue free failed, status: %d", status);
	}
	// --- END: user implements ---
}

