/**
 * @file tkl_adc.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_adc.h"
#include "osasys.h"
#include "cmsis_os2.h"
#include "ol_adc_api.h"
#include "vlog.h"

#define ADC_CHN_MAX    2
// --- END: user defines and implements ---

/**
 * @brief tuya kernel adc init
 *
 * @param[in] port_num: adc port number
 * @param[in] cfg: adc config
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_adc_init(TUYA_ADC_NUM_E port_num, TUYA_ADC_BASE_CFG_T *cfg)
{
    // --- BEGIN: user implements ---
    if (cfg == NULL || port_num >= ADC_CHN_MAX) {
        LOGE("init adc failed, invalid param, port_num/%d, cfg/%p", port_num, cfg);
        return OPRT_INVALID_PARM;
    }

    LOGD("init adc success, port_num/%d", port_num);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief adc deinit
 *
 * @param[in] port_num: adc port number

 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_adc_deinit(TUYA_ADC_NUM_E port_num)
{
    // --- BEGIN: user implements ---
    if (port_num >= ADC_CHN_MAX) {
        LOGE("deinit adc failed, invalid param, port_num/%d", port_num);
    }

    LOGD("deinit adc success, port_num/%d", port_num);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief get adc width
 *
 * @param[in] port_num: adc port number

 *
 * @return adc width
 */
uint8_t tkl_adc_width_get(TUYA_ADC_NUM_E port_num)
{
    // --- BEGIN: user implements ---
    return 12;
    // --- END: user implements ---
}

/**
 * @brief get adc reference voltage
 *
 * @param[in] port_num

 *
 * @return adc reference voltage(bat: mv)
 */
uint32_t tkl_adc_ref_voltage_get(TUYA_ADC_NUM_E port_num)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief adc get temperature
 *
 * @return temperature(bat: 'C)
 */
int32_t tkl_adc_temperature_get(void)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief adc read
 *
 * @param[in] port_num: adc port number
 * @param[out] buff: points to the list of data read from the ADC register
 * @param[in] len:  buff len
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_adc_read_data(TUYA_ADC_NUM_E port_num, int32_t *buff, uint16_t len)
{
    // --- BEGIN: user implements ---
    LOGE("adc read data not supported");
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief read single channel
 *
 * @param[in] port_num: adc port number
 * @param[in] ch_id: channel id in one adc unit
 * @param[out] buff: convert result buffer
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 *
 */
OPERATE_RET tkl_adc_read_single_channel(TUYA_ADC_NUM_E port_num, uint8_t ch_id, int32_t *data)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief read voltage
 *
 * @param[in] port_num: adc port number
 * @param[out] buff: points to the list of calculate voltage,bat : mv
 * @param[in] len:  buff len
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 *
 */
OPERATE_RET tkl_adc_read_voltage(TUYA_ADC_NUM_E port_num, int32_t *buff, uint16_t len)
{
    // --- BEGIN: user implements ---
	int32_t uV;
    if (port_num >= ADC_CHN_MAX || NULL == buff || 0 == len) {
        LOGE("read voltage failed, port_num/%d, len/%d", port_num, len);
        return OPRT_INVALID_PARM;
    }

    ol_adc_id_enum id = (port_num - TUYA_ADC_NUM_0) + OL_ADC_0;
    for (uint16_t i = 0; i < len; i++) {
        uV = ol_adc_get_vol(id);
		buff[i] = (int32_t)(uV / 1000);
    }
    return OPRT_OK;
    // --- END: user implements ---
}

