/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __ec7xx__H
#define __ec7xx__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_ec7xx(Args *args);

Arg* ec7xx_ADC(PikaObj *self);
Arg* ec7xx_GPIO(PikaObj *self);
Arg* ec7xx_IIC(PikaObj *self);
Arg* ec7xx_PWM(PikaObj *self);
Arg* ec7xx_SPI(PikaObj *self);
Arg* ec7xx_Task(PikaObj *self);
Arg* ec7xx_UART(PikaObj *self);

#endif
