/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaPythonInit(void){
    pika_platform_printf("======[pikapython packages installed]======\r\n");
    pika_printVersion();
    pika_platform_printf("PikaStdDevice==v2.4.2\r\n");
    pika_platform_printf("PikaStdLib==v1.12.6\r\n");
    pika_platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "import PikaStdLib\n"
            "import PikaStdData\n"
            "import PikaStdTask\n"
            "import ec7xx\n"
            "# print('Pika Main')\n"
            "# time = ec7xx.Time()\n"
            "# led = ec7xx.GPIO()\n"
            "# led.setPin(2)\n"
            "# led.setMode('out')\n"
            "# led.getMode()\n"
            "# led.enable()\n"
            "# led.high()\n"
            "# led.read()\n"
            "# led.low()\n"
            "# led.read()\n"
            "uar1 = ec7xx.UART()\n"
            "uar1.setId(1)\n"
            "uar1.setBaudRate(115200)\n"
            "uar1.enable()\n"
            "uar1.writeBytes(b'\\xfa\\xfe\\xfd\\xfc', 4)\n"
            "uar1.write(\"test\\r\\n\")\n"
            "uar1.readBytes(5)\n"
            "uar2 = ec7xx.UART()\n"
            "uar2.setId(2)\n"
            "uar2.setBaudRate(115200)\n"
            "uar2.enable()\n"
            "uar2.write(\"test\\r\\n\")\n"
            "uar2.writeBytes(b'\\xfa\\xfe\\xfd\\xfc', 4)\n"
            "# uar2.readBytes(5)\n"
            "# readBuff = uar2.read(2)\n"
            "# print('read 2 char:')\n"
            "# print(readBuff)\n"
            "# uar3.setPinRX(29)\n"
            "# uar3.setPinTX(30)\n"
            "uar3 = ec7xx.UART()\n"
            "uar3.setId(3)\n"
            "uar3.setBaudRate(115200)\n"
            "uar3.enable()\n"
            "uar3.write(\"test\\r\\n\")\n"
            "uar3.writeBytes(b'\\xff\\xfe\\xfd\\xfc', 4)\n"
            "spi = ec7xx.SPI()\n"
            "spi.setId(2)\n"
            "spi.enable()\n"
            "i2c = ec7xx.IIC()\n"
            "i2c.setId(1)\n"
            "i2c.enable()\n"
            "# adc = ec7xx.ADC()\n"
            "# pwm = ec7xx.PWM()\n"
            "# dac = ec7xx.DAC()\n"
            "# print('mem used max:')\n"
            "# mem.max()\n"
            "# def print_task():\n"
            "#     print('test PikaStdTask')\n"
            "#     mem.now()\n"
            "# def led_task():\n"
            "#     if led.read():\n"
            "#         led.low()\n"
            "#     else:\n"
            "#         led.high()\n"
            "# task = machine.Task()\n"
            "# task.call_period_ms(print_task, 1000)\n"
            "# task.call_period_ms(led_task, 500)\n"
            "# task.run_forever()\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

