#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.83.223, Wed Aug 12 19:50:30 2026

#define DB_VERSION_UNIQ_ID "0x5fbbd1e3"

#endif //_DB_VERSION_H
